[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py39']
include = '\.py$'
exclude = '''
(
      \.git
    | \.venv
    | /__pycache__/
)
'''

[tool.pylint.format]
max-line-length = 120
max-module-lines = 1000

[tool.pylint.similarities]
ignore-imports = "yes"
min-similarity-lines = 5

[tool.pylint.message_control]
disable=[
    "fixme"
]

[tool.pylint.basic]
good-names = ["i", "j", "k", "v", "e", "ui", "by", "pytest_plugins"]
